package corpus

import (
	"compress/gzip"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Chain is a built fixture on disk.
type Chain struct {
	Dir          string
	Producer     *Producer
	Files        []string // full paths, in chain order
	Anchors      []SignedAnchor
	IdentityPath string
}

// BuildOptions describes the fixture to build.
type BuildOptions struct {
	Dir             string
	Service         string
	ChainID         string
	Seed            byte
	Segments        int
	LinesPerSegment int
	// GzipSegments names segment indices to write compressed, exercising the transparent .gz path.
	GzipSegments map[int]bool
	// Symlink adds the stable "current file" symlink that real producers keep. A verifier that follows it
	// reads the live segment twice and reports a chain that restarts inside its own run, so every fixture
	// that can carry one should.
	Symlink bool
	// WriteIdentity puts the producer's logid.key in the directory, so a test can drive the tool the way an
	// operator would. Off by default: most tests should NOT have an identity sitting in the evidence tree.
	WriteIdentity bool
}

// Build writes a complete chain and returns what it wrote.
func Build(o BuildOptions) (*Chain, error) {
	if o.Service == "" {
		o.Service = "sc-test"
	}
	if o.ChainID == "" {
		o.ChainID = "a1b2c3d4e5f60718293a4b5c6d7e8f90"
	}
	if o.Segments <= 0 {
		o.Segments = 1
	}
	if o.LinesPerSegment <= 0 {
		o.LinesPerSegment = 4
	}

	p := New(o.Seed, o.Service, o.ChainID)
	out := &Chain{Dir: o.Dir, Producer: p}

	for s := 0; s < o.Segments; s++ {
		var b strings.Builder
		b.WriteString(p.StartSegment())
		b.WriteString("\n")
		for i := 0; i < o.LinesPerSegment; i++ {
			b.WriteString(p.Line(fmt.Sprintf("segment %d line %d", s, i)))
			b.WriteString("\n")
		}
		final := s < o.Segments-1
		out.Anchors = append(out.Anchors, p.Anchor(final))

		name := fmt.Sprintf("%s.%04d.jsonl", o.Service, s)
		if o.GzipSegments[s] {
			name += ".gz"
		}
		path := filepath.Join(o.Dir, name)
		if err := writeMaybeGzip(path, b.String(), o.GzipSegments[s]); err != nil {
			return nil, err
		}
		out.Files = append(out.Files, path)

		if s < o.Segments-1 {
			p.Rotate()
		}
	}

	if o.Symlink {
		link := filepath.Join(o.Dir, o.Service+".jsonl")
		target := filepath.Base(out.Files[len(out.Files)-1])
		if err := os.Symlink(target, link); err != nil {
			return nil, fmt.Errorf("create the live symlink: %w", err)
		}
	}

	if o.WriteIdentity {
		path, err := WriteIdentityFile(o.Dir, p)
		if err != nil {
			return nil, err
		}
		out.IdentityPath = path
	}

	return out, nil
}

// WriteIdentityFile writes the producer's identity in the on disk format of SPEC.md section 4.3.
func WriteIdentityFile(dir string, p *Producer) (string, error) {
	raw, err := json.Marshal(map[string]any{
		"comment":     "test identity, generated by the conformance corpus; worthless outside it",
		"private_key": []byte(p.Priv),
		"public_key":  []byte(p.Pub),
	})
	if err != nil {
		return "", err
	}
	path := filepath.Join(dir, "logid.key")
	if err := os.WriteFile(path, raw, 0o600); err != nil {
		return "", err
	}
	return path, nil
}

// WriteAnchor writes one anchor as JSON, the way it is handed to a customer.
func WriteAnchor(path string, sa SignedAnchor) error {
	raw, err := json.MarshalIndent(sa, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, raw, 0o644)
}

func writeMaybeGzip(path, content string, compress bool) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	if !compress {
		_, err = f.WriteString(content)
		return err
	}
	zw := gzip.NewWriter(f)
	if _, err := zw.Write([]byte(content)); err != nil {
		return err
	}
	return zw.Close()
}

// ReadLines returns a file's lines, for tests that damage evidence.
func ReadLines(path string) ([]string, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	lines := strings.Split(strings.TrimRight(string(raw), "\n"), "\n")
	return lines, nil
}

// WriteLines replaces a file's contents, for tests that damage evidence.
func WriteLines(path string, lines []string) error {
	return os.WriteFile(path, []byte(strings.Join(lines, "\n")+"\n"), 0o644)
}
